version: '3'
services:
  web:
    environment:
      - CDN_HOST=my_cdn.localhost
      - REDIS=redis://redis:6379/0
    build: .
    image: balancer:v1
    ports:
     - "80:8000"
    depends_on:
     - redis
    command: python main.py
    networks:
      - app-network
  redis:
    image: redis
    ports:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
